# https://rust-lang.github.io/rustfmt
# format_code_in_doc_comments = true # nightly
# group_imports = "StdExternalCrate" # nightly
# imports_granularity = "Crate"      # nightly
newline_style = "Unix"
hard_tabs = false
tab_spaces = 4
reorder_imports = true
reorder_modules = true